/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignupSplatRouteImport } from './routes/signup.$'
import { Route as LoginSplatRouteImport } from './routes/login.$'
import { Route as ProtectedSettingsRouteImport } from './routes/_protected.settings'
import { Route as ProtectedDashboardRouteImport } from './routes/_protected.dashboard'
import { Route as ProtectedJobsNewRouteImport } from './routes/_protected.jobs.new'
import { Route as ProtectedJobsJobIdRouteImport } from './routes/_protected.jobs.$jobId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupSplatRoute = SignupSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => SignupRoute,
} as any)
const LoginSplatRoute = LoginSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => LoginRoute,
} as any)
const ProtectedSettingsRoute = ProtectedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedJobsNewRoute = ProtectedJobsNewRouteImport.update({
  id: '/jobs/new',
  path: '/jobs/new',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedJobsJobIdRoute = ProtectedJobsJobIdRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => ProtectedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRouteWithChildren
  '/signup': typeof SignupRouteWithChildren
  '/dashboard': typeof ProtectedDashboardRoute
  '/settings': typeof ProtectedSettingsRoute
  '/login/$': typeof LoginSplatRoute
  '/signup/$': typeof SignupSplatRoute
  '/jobs/$jobId': typeof ProtectedJobsJobIdRoute
  '/jobs/new': typeof ProtectedJobsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRouteWithChildren
  '/signup': typeof SignupRouteWithChildren
  '/dashboard': typeof ProtectedDashboardRoute
  '/settings': typeof ProtectedSettingsRoute
  '/login/$': typeof LoginSplatRoute
  '/signup/$': typeof SignupSplatRoute
  '/jobs/$jobId': typeof ProtectedJobsJobIdRoute
  '/jobs/new': typeof ProtectedJobsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/login': typeof LoginRouteWithChildren
  '/signup': typeof SignupRouteWithChildren
  '/_protected/dashboard': typeof ProtectedDashboardRoute
  '/_protected/settings': typeof ProtectedSettingsRoute
  '/login/$': typeof LoginSplatRoute
  '/signup/$': typeof SignupSplatRoute
  '/_protected/jobs/$jobId': typeof ProtectedJobsJobIdRoute
  '/_protected/jobs/new': typeof ProtectedJobsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/settings'
    | '/login/$'
    | '/signup/$'
    | '/jobs/$jobId'
    | '/jobs/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/settings'
    | '/login/$'
    | '/signup/$'
    | '/jobs/$jobId'
    | '/jobs/new'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/login'
    | '/signup'
    | '/_protected/dashboard'
    | '/_protected/settings'
    | '/login/$'
    | '/signup/$'
    | '/_protected/jobs/$jobId'
    | '/_protected/jobs/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  LoginRoute: typeof LoginRouteWithChildren
  SignupRoute: typeof SignupRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/$': {
      id: '/signup/$'
      path: '/$'
      fullPath: '/signup/$'
      preLoaderRoute: typeof SignupSplatRouteImport
      parentRoute: typeof SignupRoute
    }
    '/login/$': {
      id: '/login/$'
      path: '/$'
      fullPath: '/login/$'
      preLoaderRoute: typeof LoginSplatRouteImport
      parentRoute: typeof LoginRoute
    }
    '/_protected/settings': {
      id: '/_protected/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ProtectedSettingsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/jobs/new': {
      id: '/_protected/jobs/new'
      path: '/jobs/new'
      fullPath: '/jobs/new'
      preLoaderRoute: typeof ProtectedJobsNewRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/jobs/$jobId': {
      id: '/_protected/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof ProtectedJobsJobIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedDashboardRoute: typeof ProtectedDashboardRoute
  ProtectedSettingsRoute: typeof ProtectedSettingsRoute
  ProtectedJobsJobIdRoute: typeof ProtectedJobsJobIdRoute
  ProtectedJobsNewRoute: typeof ProtectedJobsNewRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedDashboardRoute: ProtectedDashboardRoute,
  ProtectedSettingsRoute: ProtectedSettingsRoute,
  ProtectedJobsJobIdRoute: ProtectedJobsJobIdRoute,
  ProtectedJobsNewRoute: ProtectedJobsNewRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

interface LoginRouteChildren {
  LoginSplatRoute: typeof LoginSplatRoute
}

const LoginRouteChildren: LoginRouteChildren = {
  LoginSplatRoute: LoginSplatRoute,
}

const LoginRouteWithChildren = LoginRoute._addFileChildren(LoginRouteChildren)

interface SignupRouteChildren {
  SignupSplatRoute: typeof SignupSplatRoute
}

const SignupRouteChildren: SignupRouteChildren = {
  SignupSplatRoute: SignupSplatRoute,
}

const SignupRouteWithChildren =
  SignupRoute._addFileChildren(SignupRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  LoginRoute: LoginRouteWithChildren,
  SignupRoute: SignupRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
